"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class cmd_lcm2(object):
    __slots__ = ["linear", "angular"]

    def __init__(self):
        self.linear = [ 0.0 for dim0 in range(2) ]
        self.angular = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(cmd_lcm2._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>2d', *self.linear[:2]))
        buf.write(struct.pack(">d", self.angular))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != cmd_lcm2._get_packed_fingerprint():
            raise ValueError("Decode error")
        return cmd_lcm2._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = cmd_lcm2()
        self.linear = struct.unpack('>2d', buf.read(16))
        self.angular = struct.unpack(">d", buf.read(8))[0]
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if cmd_lcm2 in parents: return 0
        tmphash = (0x295cb6666cf75eef) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if cmd_lcm2._packed_fingerprint is None:
            cmd_lcm2._packed_fingerprint = struct.pack(">Q", cmd_lcm2._get_hash_recursive([]))
        return cmd_lcm2._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

