// Generated by gencpp from file map_store/DeleteMapResponse.msg
// DO NOT EDIT!


#ifndef MAP_STORE_MESSAGE_DELETEMAPRESPONSE_H
#define MAP_STORE_MESSAGE_DELETEMAPRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace map_store
{
template <class ContainerAllocator>
struct DeleteMapResponse_
{
  typedef DeleteMapResponse_<ContainerAllocator> Type;

  DeleteMapResponse_()
    {
    }
  DeleteMapResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::map_store::DeleteMapResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::map_store::DeleteMapResponse_<ContainerAllocator> const> ConstPtr;

}; // struct DeleteMapResponse_

typedef ::map_store::DeleteMapResponse_<std::allocator<void> > DeleteMapResponse;

typedef boost::shared_ptr< ::map_store::DeleteMapResponse > DeleteMapResponsePtr;
typedef boost::shared_ptr< ::map_store::DeleteMapResponse const> DeleteMapResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::map_store::DeleteMapResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::map_store::DeleteMapResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace map_store

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::map_store::DeleteMapResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::map_store::DeleteMapResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::map_store::DeleteMapResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::map_store::DeleteMapResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::map_store::DeleteMapResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::map_store::DeleteMapResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::map_store::DeleteMapResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::map_store::DeleteMapResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::map_store::DeleteMapResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "map_store/DeleteMapResponse";
  }

  static const char* value(const ::map_store::DeleteMapResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::map_store::DeleteMapResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::map_store::DeleteMapResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::map_store::DeleteMapResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DeleteMapResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::map_store::DeleteMapResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::map_store::DeleteMapResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // MAP_STORE_MESSAGE_DELETEMAPRESPONSE_H
