// Generated by gencpp from file map_store/SetOrigin.msg
// DO NOT EDIT!


#ifndef MAP_STORE_MESSAGE_SETORIGIN_H
#define MAP_STORE_MESSAGE_SETORIGIN_H

#include <ros/service_traits.h>


#include <map_store/SetOriginRequest.h>
#include <map_store/SetOriginResponse.h>


namespace map_store
{

struct SetOrigin
{

typedef SetOriginRequest Request;
typedef SetOriginResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetOrigin
} // namespace map_store


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::map_store::SetOrigin > {
  static const char* value()
  {
    return "9c17e99b9635aa83a73123978f777ac2";
  }

  static const char* value(const ::map_store::SetOrigin&) { return value(); }
};

template<>
struct DataType< ::map_store::SetOrigin > {
  static const char* value()
  {
    return "map_store/SetOrigin";
  }

  static const char* value(const ::map_store::SetOrigin&) { return value(); }
};


// service_traits::MD5Sum< ::map_store::SetOriginRequest> should match
// service_traits::MD5Sum< ::map_store::SetOrigin >
template<>
struct MD5Sum< ::map_store::SetOriginRequest>
{
  static const char* value()
  {
    return MD5Sum< ::map_store::SetOrigin >::value();
  }
  static const char* value(const ::map_store::SetOriginRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::map_store::SetOriginRequest> should match
// service_traits::DataType< ::map_store::SetOrigin >
template<>
struct DataType< ::map_store::SetOriginRequest>
{
  static const char* value()
  {
    return DataType< ::map_store::SetOrigin >::value();
  }
  static const char* value(const ::map_store::SetOriginRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::map_store::SetOriginResponse> should match
// service_traits::MD5Sum< ::map_store::SetOrigin >
template<>
struct MD5Sum< ::map_store::SetOriginResponse>
{
  static const char* value()
  {
    return MD5Sum< ::map_store::SetOrigin >::value();
  }
  static const char* value(const ::map_store::SetOriginResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::map_store::SetOriginResponse> should match
// service_traits::DataType< ::map_store::SetOrigin >
template<>
struct DataType< ::map_store::SetOriginResponse>
{
  static const char* value()
  {
    return DataType< ::map_store::SetOrigin >::value();
  }
  static const char* value(const ::map_store::SetOriginResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MAP_STORE_MESSAGE_SETORIGIN_H
