// Generated by gencpp from file map_store/SetOriginRequest.msg
// DO NOT EDIT!


#ifndef MAP_STORE_MESSAGE_SETORIGINREQUEST_H
#define MAP_STORE_MESSAGE_SETORIGINREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace map_store
{
template <class ContainerAllocator>
struct SetOriginRequest_
{
  typedef SetOriginRequest_<ContainerAllocator> Type;

  SetOriginRequest_()
    : map_id()
    , pos_x(0.0)
    , pos_y(0.0)
    , rot_x(0.0)
    , rot_y(0.0)
    , rot_z(0.0)
    , rot_w(0.0)  {
    }
  SetOriginRequest_(const ContainerAllocator& _alloc)
    : map_id(_alloc)
    , pos_x(0.0)
    , pos_y(0.0)
    , rot_x(0.0)
    , rot_y(0.0)
    , rot_z(0.0)
    , rot_w(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _map_id_type;
  _map_id_type map_id;

   typedef float _pos_x_type;
  _pos_x_type pos_x;

   typedef float _pos_y_type;
  _pos_y_type pos_y;

   typedef float _rot_x_type;
  _rot_x_type rot_x;

   typedef float _rot_y_type;
  _rot_y_type rot_y;

   typedef float _rot_z_type;
  _rot_z_type rot_z;

   typedef float _rot_w_type;
  _rot_w_type rot_w;





  typedef boost::shared_ptr< ::map_store::SetOriginRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::map_store::SetOriginRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetOriginRequest_

typedef ::map_store::SetOriginRequest_<std::allocator<void> > SetOriginRequest;

typedef boost::shared_ptr< ::map_store::SetOriginRequest > SetOriginRequestPtr;
typedef boost::shared_ptr< ::map_store::SetOriginRequest const> SetOriginRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::map_store::SetOriginRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::map_store::SetOriginRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::map_store::SetOriginRequest_<ContainerAllocator1> & lhs, const ::map_store::SetOriginRequest_<ContainerAllocator2> & rhs)
{
  return lhs.map_id == rhs.map_id &&
    lhs.pos_x == rhs.pos_x &&
    lhs.pos_y == rhs.pos_y &&
    lhs.rot_x == rhs.rot_x &&
    lhs.rot_y == rhs.rot_y &&
    lhs.rot_z == rhs.rot_z &&
    lhs.rot_w == rhs.rot_w;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::map_store::SetOriginRequest_<ContainerAllocator1> & lhs, const ::map_store::SetOriginRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace map_store

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::map_store::SetOriginRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::map_store::SetOriginRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::map_store::SetOriginRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::map_store::SetOriginRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::map_store::SetOriginRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::map_store::SetOriginRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::map_store::SetOriginRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9c17e99b9635aa83a73123978f777ac2";
  }

  static const char* value(const ::map_store::SetOriginRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9c17e99b9635aa83ULL;
  static const uint64_t static_value2 = 0xa73123978f777ac2ULL;
};

template<class ContainerAllocator>
struct DataType< ::map_store::SetOriginRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "map_store/SetOriginRequest";
  }

  static const char* value(const ::map_store::SetOriginRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::map_store::SetOriginRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Service used to set the map origin dynamically\n"
"string map_id\n"
"\n"
"float32 pos_x\n"
"float32 pos_y\n"
"\n"
"float32 rot_x\n"
"float32 rot_y\n"
"float32 rot_z\n"
"float32 rot_w\n"
;
  }

  static const char* value(const ::map_store::SetOriginRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::map_store::SetOriginRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.map_id);
      stream.next(m.pos_x);
      stream.next(m.pos_y);
      stream.next(m.rot_x);
      stream.next(m.rot_y);
      stream.next(m.rot_z);
      stream.next(m.rot_w);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetOriginRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::map_store::SetOriginRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::map_store::SetOriginRequest_<ContainerAllocator>& v)
  {
    s << indent << "map_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.map_id);
    s << indent << "pos_x: ";
    Printer<float>::stream(s, indent + "  ", v.pos_x);
    s << indent << "pos_y: ";
    Printer<float>::stream(s, indent + "  ", v.pos_y);
    s << indent << "rot_x: ";
    Printer<float>::stream(s, indent + "  ", v.rot_x);
    s << indent << "rot_y: ";
    Printer<float>::stream(s, indent + "  ", v.rot_y);
    s << indent << "rot_z: ";
    Printer<float>::stream(s, indent + "  ", v.rot_z);
    s << indent << "rot_w: ";
    Printer<float>::stream(s, indent + "  ", v.rot_w);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAP_STORE_MESSAGE_SETORIGINREQUEST_H
