; Auto-generated. Do not edit!


(cl:in-package multi_map_navigation-msg)


;//! \htmlinclude MultiMapNavigationTransitionFeedback.msg.html

(cl:defclass <MultiMapNavigationTransitionFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass MultiMapNavigationTransitionFeedback (<MultiMapNavigationTransitionFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <MultiMapNavigationTransitionFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'MultiMapNavigationTransitionFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name multi_map_navigation-msg:<MultiMapNavigationTransitionFeedback> is deprecated: use multi_map_navigation-msg:MultiMapNavigationTransitionFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <MultiMapNavigationTransitionFeedback>) ostream)
  "Serializes a message object of type '<MultiMapNavigationTransitionFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <MultiMapNavigationTransitionFeedback>) istream)
  "Deserializes a message object of type '<MultiMapNavigationTransitionFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<MultiMapNavigationTransitionFeedback>)))
  "Returns string type for a message object of type '<MultiMapNavigationTransitionFeedback>"
  "multi_map_navigation/MultiMapNavigationTransitionFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'MultiMapNavigationTransitionFeedback)))
  "Returns string type for a message object of type 'MultiMapNavigationTransitionFeedback"
  "multi_map_navigation/MultiMapNavigationTransitionFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<MultiMapNavigationTransitionFeedback>)))
  "Returns md5sum for a message object of type '<MultiMapNavigationTransitionFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'MultiMapNavigationTransitionFeedback)))
  "Returns md5sum for a message object of type 'MultiMapNavigationTransitionFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<MultiMapNavigationTransitionFeedback>)))
  "Returns full string definition for message of type '<MultiMapNavigationTransitionFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'MultiMapNavigationTransitionFeedback)))
  "Returns full string definition for message of type 'MultiMapNavigationTransitionFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <MultiMapNavigationTransitionFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <MultiMapNavigationTransitionFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'MultiMapNavigationTransitionFeedback
))
