; Auto-generated. Do not edit!


(cl:in-package multi_map_navigation-msg)


;//! \htmlinclude MultiMapNavigationGoal.msg.html

(cl:defclass <MultiMapNavigationGoal> (roslisp-msg-protocol:ros-message)
  ((target_pose
    :reader target_pose
    :initarg :target_pose
    :type geometry_msgs-msg:PoseStamped
    :initform (cl:make-instance 'geometry_msgs-msg:PoseStamped))
   (goal_map
    :reader goal_map
    :initarg :goal_map
    :type cl:string
    :initform ""))
)

(cl:defclass MultiMapNavigationGoal (<MultiMapNavigationGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <MultiMapNavigationGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'MultiMapNavigationGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name multi_map_navigation-msg:<MultiMapNavigationGoal> is deprecated: use multi_map_navigation-msg:MultiMapNavigationGoal instead.")))

(cl:ensure-generic-function 'target_pose-val :lambda-list '(m))
(cl:defmethod target_pose-val ((m <MultiMapNavigationGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader multi_map_navigation-msg:target_pose-val is deprecated.  Use multi_map_navigation-msg:target_pose instead.")
  (target_pose m))

(cl:ensure-generic-function 'goal_map-val :lambda-list '(m))
(cl:defmethod goal_map-val ((m <MultiMapNavigationGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader multi_map_navigation-msg:goal_map-val is deprecated.  Use multi_map_navigation-msg:goal_map instead.")
  (goal_map m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <MultiMapNavigationGoal>) ostream)
  "Serializes a message object of type '<MultiMapNavigationGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'target_pose) ostream)
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'goal_map))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'goal_map))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <MultiMapNavigationGoal>) istream)
  "Deserializes a message object of type '<MultiMapNavigationGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'target_pose) istream)
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'goal_map) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'goal_map) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<MultiMapNavigationGoal>)))
  "Returns string type for a message object of type '<MultiMapNavigationGoal>"
  "multi_map_navigation/MultiMapNavigationGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'MultiMapNavigationGoal)))
  "Returns string type for a message object of type 'MultiMapNavigationGoal"
  "multi_map_navigation/MultiMapNavigationGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<MultiMapNavigationGoal>)))
  "Returns md5sum for a message object of type '<MultiMapNavigationGoal>"
  "47922f5c2738d0955979038029fc03b5")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'MultiMapNavigationGoal)))
  "Returns md5sum for a message object of type 'MultiMapNavigationGoal"
  "47922f5c2738d0955979038029fc03b5")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<MultiMapNavigationGoal>)))
  "Returns full string definition for message of type '<MultiMapNavigationGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%geometry_msgs/PoseStamped target_pose~%string goal_map~%~%================================================================================~%MSG: geometry_msgs/PoseStamped~%# A Pose with reference coordinate frame and timestamp~%Header header~%Pose pose~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'MultiMapNavigationGoal)))
  "Returns full string definition for message of type 'MultiMapNavigationGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%geometry_msgs/PoseStamped target_pose~%string goal_map~%~%================================================================================~%MSG: geometry_msgs/PoseStamped~%# A Pose with reference coordinate frame and timestamp~%Header header~%Pose pose~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <MultiMapNavigationGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'target_pose))
     4 (cl:length (cl:slot-value msg 'goal_map))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <MultiMapNavigationGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'MultiMapNavigationGoal
    (cl:cons ':target_pose (target_pose msg))
    (cl:cons ':goal_map (goal_map msg))
))
