; Auto-generated. Do not edit!


(cl:in-package multi_map_navigation-msg)


;//! \htmlinclude MultiMapNavigationTransitionResult.msg.html

(cl:defclass <MultiMapNavigationTransitionResult> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass MultiMapNavigationTransitionResult (<MultiMapNavigationTransitionResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <MultiMapNavigationTransitionResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'MultiMapNavigationTransitionResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name multi_map_navigation-msg:<MultiMapNavigationTransitionResult> is deprecated: use multi_map_navigation-msg:MultiMapNavigationTransitionResult instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <MultiMapNavigationTransitionResult>) ostream)
  "Serializes a message object of type '<MultiMapNavigationTransitionResult>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <MultiMapNavigationTransitionResult>) istream)
  "Deserializes a message object of type '<MultiMapNavigationTransitionResult>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<MultiMapNavigationTransitionResult>)))
  "Returns string type for a message object of type '<MultiMapNavigationTransitionResult>"
  "multi_map_navigation/MultiMapNavigationTransitionResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'MultiMapNavigationTransitionResult)))
  "Returns string type for a message object of type 'MultiMapNavigationTransitionResult"
  "multi_map_navigation/MultiMapNavigationTransitionResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<MultiMapNavigationTransitionResult>)))
  "Returns md5sum for a message object of type '<MultiMapNavigationTransitionResult>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'MultiMapNavigationTransitionResult)))
  "Returns md5sum for a message object of type 'MultiMapNavigationTransitionResult"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<MultiMapNavigationTransitionResult>)))
  "Returns full string definition for message of type '<MultiMapNavigationTransitionResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'MultiMapNavigationTransitionResult)))
  "Returns full string definition for message of type 'MultiMapNavigationTransitionResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <MultiMapNavigationTransitionResult>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <MultiMapNavigationTransitionResult>))
  "Converts a ROS message object to a list"
  (cl:list 'MultiMapNavigationTransitionResult
))
