; Auto-generated. Do not edit!


(cl:in-package multi_map_navigation-msg)


;//! \htmlinclude MultiMapNavigationResult.msg.html

(cl:defclass <MultiMapNavigationResult> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass MultiMapNavigationResult (<MultiMapNavigationResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <MultiMapNavigationResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'MultiMapNavigationResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name multi_map_navigation-msg:<MultiMapNavigationResult> is deprecated: use multi_map_navigation-msg:MultiMapNavigationResult instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <MultiMapNavigationResult>) ostream)
  "Serializes a message object of type '<MultiMapNavigationResult>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <MultiMapNavigationResult>) istream)
  "Deserializes a message object of type '<MultiMapNavigationResult>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<MultiMapNavigationResult>)))
  "Returns string type for a message object of type '<MultiMapNavigationResult>"
  "multi_map_navigation/MultiMapNavigationResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'MultiMapNavigationResult)))
  "Returns string type for a message object of type 'MultiMapNavigationResult"
  "multi_map_navigation/MultiMapNavigationResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<MultiMapNavigationResult>)))
  "Returns md5sum for a message object of type '<MultiMapNavigationResult>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'MultiMapNavigationResult)))
  "Returns md5sum for a message object of type 'MultiMapNavigationResult"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<MultiMapNavigationResult>)))
  "Returns full string definition for message of type '<MultiMapNavigationResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'MultiMapNavigationResult)))
  "Returns full string definition for message of type 'MultiMapNavigationResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <MultiMapNavigationResult>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <MultiMapNavigationResult>))
  "Converts a ROS message object to a list"
  (cl:list 'MultiMapNavigationResult
))
