; Auto-generated. Do not edit!


(cl:in-package multi_map_navigation-msg)


;//! \htmlinclude MultiMapNavigationFeedback.msg.html

(cl:defclass <MultiMapNavigationFeedback> (roslisp-msg-protocol:ros-message)
  ((base_position
    :reader base_position
    :initarg :base_position
    :type geometry_msgs-msg:PoseStamped
    :initform (cl:make-instance 'geometry_msgs-msg:PoseStamped))
   (current_map
    :reader current_map
    :initarg :current_map
    :type cl:string
    :initform ""))
)

(cl:defclass MultiMapNavigationFeedback (<MultiMapNavigationFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <MultiMapNavigationFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'MultiMapNavigationFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name multi_map_navigation-msg:<MultiMapNavigationFeedback> is deprecated: use multi_map_navigation-msg:MultiMapNavigationFeedback instead.")))

(cl:ensure-generic-function 'base_position-val :lambda-list '(m))
(cl:defmethod base_position-val ((m <MultiMapNavigationFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader multi_map_navigation-msg:base_position-val is deprecated.  Use multi_map_navigation-msg:base_position instead.")
  (base_position m))

(cl:ensure-generic-function 'current_map-val :lambda-list '(m))
(cl:defmethod current_map-val ((m <MultiMapNavigationFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader multi_map_navigation-msg:current_map-val is deprecated.  Use multi_map_navigation-msg:current_map instead.")
  (current_map m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <MultiMapNavigationFeedback>) ostream)
  "Serializes a message object of type '<MultiMapNavigationFeedback>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'base_position) ostream)
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'current_map))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'current_map))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <MultiMapNavigationFeedback>) istream)
  "Deserializes a message object of type '<MultiMapNavigationFeedback>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'base_position) istream)
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'current_map) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'current_map) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<MultiMapNavigationFeedback>)))
  "Returns string type for a message object of type '<MultiMapNavigationFeedback>"
  "multi_map_navigation/MultiMapNavigationFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'MultiMapNavigationFeedback)))
  "Returns string type for a message object of type 'MultiMapNavigationFeedback"
  "multi_map_navigation/MultiMapNavigationFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<MultiMapNavigationFeedback>)))
  "Returns md5sum for a message object of type '<MultiMapNavigationFeedback>"
  "eb14c278a594f8ede17a4a64e99892fa")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'MultiMapNavigationFeedback)))
  "Returns md5sum for a message object of type 'MultiMapNavigationFeedback"
  "eb14c278a594f8ede17a4a64e99892fa")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<MultiMapNavigationFeedback>)))
  "Returns full string definition for message of type '<MultiMapNavigationFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%geometry_msgs/PoseStamped base_position~%string current_map~%~%================================================================================~%MSG: geometry_msgs/PoseStamped~%# A Pose with reference coordinate frame and timestamp~%Header header~%Pose pose~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'MultiMapNavigationFeedback)))
  "Returns full string definition for message of type 'MultiMapNavigationFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%geometry_msgs/PoseStamped base_position~%string current_map~%~%================================================================================~%MSG: geometry_msgs/PoseStamped~%# A Pose with reference coordinate frame and timestamp~%Header header~%Pose pose~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <MultiMapNavigationFeedback>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'base_position))
     4 (cl:length (cl:slot-value msg 'current_map))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <MultiMapNavigationFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'MultiMapNavigationFeedback
    (cl:cons ':base_position (base_position msg))
    (cl:cons ':current_map (current_map msg))
))
