// Auto-generated. Do not edit!

// (in-package multi_map_navigation.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class MultiMapNavigationTransitionGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.wormhole = null;
      this.start = null;
      this.end = null;
    }
    else {
      if (initObj.hasOwnProperty('wormhole')) {
        this.wormhole = initObj.wormhole
      }
      else {
        this.wormhole = '';
      }
      if (initObj.hasOwnProperty('start')) {
        this.start = initObj.start
      }
      else {
        this.start = 0;
      }
      if (initObj.hasOwnProperty('end')) {
        this.end = initObj.end
      }
      else {
        this.end = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type MultiMapNavigationTransitionGoal
    // Serialize message field [wormhole]
    bufferOffset = _serializer.string(obj.wormhole, buffer, bufferOffset);
    // Serialize message field [start]
    bufferOffset = _serializer.int32(obj.start, buffer, bufferOffset);
    // Serialize message field [end]
    bufferOffset = _serializer.int32(obj.end, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type MultiMapNavigationTransitionGoal
    let len;
    let data = new MultiMapNavigationTransitionGoal(null);
    // Deserialize message field [wormhole]
    data.wormhole = _deserializer.string(buffer, bufferOffset);
    // Deserialize message field [start]
    data.start = _deserializer.int32(buffer, bufferOffset);
    // Deserialize message field [end]
    data.end = _deserializer.int32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += object.wormhole.length;
    return length + 12;
  }

  static datatype() {
    // Returns string type for a message object
    return 'multi_map_navigation/MultiMapNavigationTransitionGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '5b23d9c1c602bed1aeb3537d1b61abd3';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    string wormhole
    int32 start
    int32 end
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new MultiMapNavigationTransitionGoal(null);
    if (msg.wormhole !== undefined) {
      resolved.wormhole = msg.wormhole;
    }
    else {
      resolved.wormhole = ''
    }

    if (msg.start !== undefined) {
      resolved.start = msg.start;
    }
    else {
      resolved.start = 0
    }

    if (msg.end !== undefined) {
      resolved.end = msg.end;
    }
    else {
      resolved.end = 0
    }

    return resolved;
    }
};

module.exports = MultiMapNavigationTransitionGoal;
