// Auto-generated. Do not edit!

// (in-package multi_map_navigation.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let geometry_msgs = _finder('geometry_msgs');

//-----------------------------------------------------------

class MultiMapNavigationFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.base_position = null;
      this.current_map = null;
    }
    else {
      if (initObj.hasOwnProperty('base_position')) {
        this.base_position = initObj.base_position
      }
      else {
        this.base_position = new geometry_msgs.msg.PoseStamped();
      }
      if (initObj.hasOwnProperty('current_map')) {
        this.current_map = initObj.current_map
      }
      else {
        this.current_map = '';
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type MultiMapNavigationFeedback
    // Serialize message field [base_position]
    bufferOffset = geometry_msgs.msg.PoseStamped.serialize(obj.base_position, buffer, bufferOffset);
    // Serialize message field [current_map]
    bufferOffset = _serializer.string(obj.current_map, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type MultiMapNavigationFeedback
    let len;
    let data = new MultiMapNavigationFeedback(null);
    // Deserialize message field [base_position]
    data.base_position = geometry_msgs.msg.PoseStamped.deserialize(buffer, bufferOffset);
    // Deserialize message field [current_map]
    data.current_map = _deserializer.string(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += geometry_msgs.msg.PoseStamped.getMessageSize(object.base_position);
    length += object.current_map.length;
    return length + 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'multi_map_navigation/MultiMapNavigationFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'eb14c278a594f8ede17a4a64e99892fa';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    geometry_msgs/PoseStamped base_position
    string current_map
    
    ================================================================================
    MSG: geometry_msgs/PoseStamped
    # A Pose with reference coordinate frame and timestamp
    Header header
    Pose pose
    
    ================================================================================
    MSG: std_msgs/Header
    # Standard metadata for higher-level stamped data types.
    # This is generally used to communicate timestamped data 
    # in a particular coordinate frame.
    # 
    # sequence ID: consecutively increasing ID 
    uint32 seq
    #Two-integer timestamp that is expressed as:
    # * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
    # * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
    # time-handling sugar is provided by the client library
    time stamp
    #Frame this data is associated with
    string frame_id
    
    ================================================================================
    MSG: geometry_msgs/Pose
    # A representation of pose in free space, composed of position and orientation. 
    Point position
    Quaternion orientation
    
    ================================================================================
    MSG: geometry_msgs/Point
    # This contains the position of a point in free space
    float64 x
    float64 y
    float64 z
    
    ================================================================================
    MSG: geometry_msgs/Quaternion
    # This represents an orientation in free space in quaternion form.
    
    float64 x
    float64 y
    float64 z
    float64 w
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new MultiMapNavigationFeedback(null);
    if (msg.base_position !== undefined) {
      resolved.base_position = geometry_msgs.msg.PoseStamped.Resolve(msg.base_position)
    }
    else {
      resolved.base_position = new geometry_msgs.msg.PoseStamped()
    }

    if (msg.current_map !== undefined) {
      resolved.current_map = msg.current_map;
    }
    else {
      resolved.current_map = ''
    }

    return resolved;
    }
};

module.exports = MultiMapNavigationFeedback;
