// Generated by gencpp from file multi_map_navigation/MultiMapNavigationTransitionFeedback.msg
// DO NOT EDIT!


#ifndef MULTI_MAP_NAVIGATION_MESSAGE_MULTIMAPNAVIGATIONTRANSITIONFEEDBACK_H
#define MULTI_MAP_NAVIGATION_MESSAGE_MULTIMAPNAVIGATIONTRANSITIONFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace multi_map_navigation
{
template <class ContainerAllocator>
struct MultiMapNavigationTransitionFeedback_
{
  typedef MultiMapNavigationTransitionFeedback_<ContainerAllocator> Type;

  MultiMapNavigationTransitionFeedback_()
    {
    }
  MultiMapNavigationTransitionFeedback_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::multi_map_navigation::MultiMapNavigationTransitionFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::multi_map_navigation::MultiMapNavigationTransitionFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct MultiMapNavigationTransitionFeedback_

typedef ::multi_map_navigation::MultiMapNavigationTransitionFeedback_<std::allocator<void> > MultiMapNavigationTransitionFeedback;

typedef boost::shared_ptr< ::multi_map_navigation::MultiMapNavigationTransitionFeedback > MultiMapNavigationTransitionFeedbackPtr;
typedef boost::shared_ptr< ::multi_map_navigation::MultiMapNavigationTransitionFeedback const> MultiMapNavigationTransitionFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::multi_map_navigation::MultiMapNavigationTransitionFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::multi_map_navigation::MultiMapNavigationTransitionFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace multi_map_navigation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::multi_map_navigation::MultiMapNavigationTransitionFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::multi_map_navigation::MultiMapNavigationTransitionFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::multi_map_navigation::MultiMapNavigationTransitionFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::multi_map_navigation::MultiMapNavigationTransitionFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::multi_map_navigation::MultiMapNavigationTransitionFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::multi_map_navigation::MultiMapNavigationTransitionFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::multi_map_navigation::MultiMapNavigationTransitionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::multi_map_navigation::MultiMapNavigationTransitionFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::multi_map_navigation::MultiMapNavigationTransitionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "multi_map_navigation/MultiMapNavigationTransitionFeedback";
  }

  static const char* value(const ::multi_map_navigation::MultiMapNavigationTransitionFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::multi_map_navigation::MultiMapNavigationTransitionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
;
  }

  static const char* value(const ::multi_map_navigation::MultiMapNavigationTransitionFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::multi_map_navigation::MultiMapNavigationTransitionFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MultiMapNavigationTransitionFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::multi_map_navigation::MultiMapNavigationTransitionFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::multi_map_navigation::MultiMapNavigationTransitionFeedback_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // MULTI_MAP_NAVIGATION_MESSAGE_MULTIMAPNAVIGATIONTRANSITIONFEEDBACK_H
