// Generated by gencpp from file multi_map_navigation/MultiMapNavigationGoal.msg
// DO NOT EDIT!


#ifndef MULTI_MAP_NAVIGATION_MESSAGE_MULTIMAPNAVIGATIONGOAL_H
#define MULTI_MAP_NAVIGATION_MESSAGE_MULTIMAPNAVIGATIONGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>

namespace multi_map_navigation
{
template <class ContainerAllocator>
struct MultiMapNavigationGoal_
{
  typedef MultiMapNavigationGoal_<ContainerAllocator> Type;

  MultiMapNavigationGoal_()
    : target_pose()
    , goal_map()  {
    }
  MultiMapNavigationGoal_(const ContainerAllocator& _alloc)
    : target_pose(_alloc)
    , goal_map(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _target_pose_type;
  _target_pose_type target_pose;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _goal_map_type;
  _goal_map_type goal_map;





  typedef boost::shared_ptr< ::multi_map_navigation::MultiMapNavigationGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::multi_map_navigation::MultiMapNavigationGoal_<ContainerAllocator> const> ConstPtr;

}; // struct MultiMapNavigationGoal_

typedef ::multi_map_navigation::MultiMapNavigationGoal_<std::allocator<void> > MultiMapNavigationGoal;

typedef boost::shared_ptr< ::multi_map_navigation::MultiMapNavigationGoal > MultiMapNavigationGoalPtr;
typedef boost::shared_ptr< ::multi_map_navigation::MultiMapNavigationGoal const> MultiMapNavigationGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::multi_map_navigation::MultiMapNavigationGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::multi_map_navigation::MultiMapNavigationGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::multi_map_navigation::MultiMapNavigationGoal_<ContainerAllocator1> & lhs, const ::multi_map_navigation::MultiMapNavigationGoal_<ContainerAllocator2> & rhs)
{
  return lhs.target_pose == rhs.target_pose &&
    lhs.goal_map == rhs.goal_map;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::multi_map_navigation::MultiMapNavigationGoal_<ContainerAllocator1> & lhs, const ::multi_map_navigation::MultiMapNavigationGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace multi_map_navigation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::multi_map_navigation::MultiMapNavigationGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::multi_map_navigation::MultiMapNavigationGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::multi_map_navigation::MultiMapNavigationGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::multi_map_navigation::MultiMapNavigationGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::multi_map_navigation::MultiMapNavigationGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::multi_map_navigation::MultiMapNavigationGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::multi_map_navigation::MultiMapNavigationGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "47922f5c2738d0955979038029fc03b5";
  }

  static const char* value(const ::multi_map_navigation::MultiMapNavigationGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x47922f5c2738d095ULL;
  static const uint64_t static_value2 = 0x5979038029fc03b5ULL;
};

template<class ContainerAllocator>
struct DataType< ::multi_map_navigation::MultiMapNavigationGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "multi_map_navigation/MultiMapNavigationGoal";
  }

  static const char* value(const ::multi_map_navigation::MultiMapNavigationGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::multi_map_navigation::MultiMapNavigationGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"geometry_msgs/PoseStamped target_pose\n"
"string goal_map\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::multi_map_navigation::MultiMapNavigationGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::multi_map_navigation::MultiMapNavigationGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.target_pose);
      stream.next(m.goal_map);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MultiMapNavigationGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::multi_map_navigation::MultiMapNavigationGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::multi_map_navigation::MultiMapNavigationGoal_<ContainerAllocator>& v)
  {
    s << indent << "target_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.target_pose);
    s << indent << "goal_map: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.goal_map);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MULTI_MAP_NAVIGATION_MESSAGE_MULTIMAPNAVIGATIONGOAL_H
