// Generated by gencpp from file multi_map_navigation/SetMap.msg
// DO NOT EDIT!


#ifndef MULTI_MAP_NAVIGATION_MESSAGE_SETMAP_H
#define MULTI_MAP_NAVIGATION_MESSAGE_SETMAP_H

#include <ros/service_traits.h>


#include <multi_map_navigation/SetMapRequest.h>
#include <multi_map_navigation/SetMapResponse.h>


namespace multi_map_navigation
{

struct SetMap
{

typedef SetMapRequest Request;
typedef SetMapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetMap
} // namespace multi_map_navigation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::multi_map_navigation::SetMap > {
  static const char* value()
  {
    return "c1f3d28f1b044c871e6eff2e9fc3c667";
  }

  static const char* value(const ::multi_map_navigation::SetMap&) { return value(); }
};

template<>
struct DataType< ::multi_map_navigation::SetMap > {
  static const char* value()
  {
    return "multi_map_navigation/SetMap";
  }

  static const char* value(const ::multi_map_navigation::SetMap&) { return value(); }
};


// service_traits::MD5Sum< ::multi_map_navigation::SetMapRequest> should match
// service_traits::MD5Sum< ::multi_map_navigation::SetMap >
template<>
struct MD5Sum< ::multi_map_navigation::SetMapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::multi_map_navigation::SetMap >::value();
  }
  static const char* value(const ::multi_map_navigation::SetMapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::multi_map_navigation::SetMapRequest> should match
// service_traits::DataType< ::multi_map_navigation::SetMap >
template<>
struct DataType< ::multi_map_navigation::SetMapRequest>
{
  static const char* value()
  {
    return DataType< ::multi_map_navigation::SetMap >::value();
  }
  static const char* value(const ::multi_map_navigation::SetMapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::multi_map_navigation::SetMapResponse> should match
// service_traits::MD5Sum< ::multi_map_navigation::SetMap >
template<>
struct MD5Sum< ::multi_map_navigation::SetMapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::multi_map_navigation::SetMap >::value();
  }
  static const char* value(const ::multi_map_navigation::SetMapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::multi_map_navigation::SetMapResponse> should match
// service_traits::DataType< ::multi_map_navigation::SetMap >
template<>
struct DataType< ::multi_map_navigation::SetMapResponse>
{
  static const char* value()
  {
    return DataType< ::multi_map_navigation::SetMap >::value();
  }
  static const char* value(const ::multi_map_navigation::SetMapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MULTI_MAP_NAVIGATION_MESSAGE_SETMAP_H
