(cl:defpackage object_msgs-srv
  (:use )
  (:export
   "CLASSIFYOBJECT"
   "<CLASSIFYOBJECT-REQUEST>"
   "CLASSIFYOBJECT-REQUEST"
   "<CLASSIFYOBJECT-RESPONSE>"
   "CLASSIFYOBJECT-RESPONSE"
   "DETECTOBJECT"
   "<DETECTOBJECT-REQUEST>"
   "DETECTOBJECT-REQUEST"
   "<DETECTOBJECT-RESPONSE>"
   "DETECTOBJECT-RESPONSE"
  ))

