// Generated by gencpp from file object_msgs/ClassifyObjectResponse.msg
// DO NOT EDIT!


#ifndef OBJECT_MSGS_MESSAGE_CLASSIFYOBJECTRESPONSE_H
#define OBJECT_MSGS_MESSAGE_CLASSIFYOBJECTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <object_msgs/Objects.h>

namespace object_msgs
{
template <class ContainerAllocator>
struct ClassifyObjectResponse_
{
  typedef ClassifyObjectResponse_<ContainerAllocator> Type;

  ClassifyObjectResponse_()
    : objects()  {
    }
  ClassifyObjectResponse_(const ContainerAllocator& _alloc)
    : objects(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::object_msgs::Objects_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::object_msgs::Objects_<ContainerAllocator> >::other >  _objects_type;
  _objects_type objects;





  typedef boost::shared_ptr< ::object_msgs::ClassifyObjectResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::object_msgs::ClassifyObjectResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ClassifyObjectResponse_

typedef ::object_msgs::ClassifyObjectResponse_<std::allocator<void> > ClassifyObjectResponse;

typedef boost::shared_ptr< ::object_msgs::ClassifyObjectResponse > ClassifyObjectResponsePtr;
typedef boost::shared_ptr< ::object_msgs::ClassifyObjectResponse const> ClassifyObjectResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::object_msgs::ClassifyObjectResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::object_msgs::ClassifyObjectResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::object_msgs::ClassifyObjectResponse_<ContainerAllocator1> & lhs, const ::object_msgs::ClassifyObjectResponse_<ContainerAllocator2> & rhs)
{
  return lhs.objects == rhs.objects;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::object_msgs::ClassifyObjectResponse_<ContainerAllocator1> & lhs, const ::object_msgs::ClassifyObjectResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace object_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::object_msgs::ClassifyObjectResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::object_msgs::ClassifyObjectResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::object_msgs::ClassifyObjectResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::object_msgs::ClassifyObjectResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::object_msgs::ClassifyObjectResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::object_msgs::ClassifyObjectResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::object_msgs::ClassifyObjectResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c45ac40244fa3f6f402edea4d64747ae";
  }

  static const char* value(const ::object_msgs::ClassifyObjectResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc45ac40244fa3f6fULL;
  static const uint64_t static_value2 = 0x402edea4d64747aeULL;
};

template<class ContainerAllocator>
struct DataType< ::object_msgs::ClassifyObjectResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "object_msgs/ClassifyObjectResponse";
  }

  static const char* value(const ::object_msgs::ClassifyObjectResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::object_msgs::ClassifyObjectResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Objects[] objects     # bounding box list for each of inferred images\n"
"\n"
"\n"
"================================================================================\n"
"MSG: object_msgs/Objects\n"
"# Copyright (c) 2017 Intel Corporation\n"
"#\n"
"# Licensed under the Apache License, Version 2.0 (the \"License\");\n"
"# you may not use this file except in compliance with the License.\n"
"# You may obtain a copy of the License at\n"
"#\n"
"#      http://www.apache.org/licenses/LICENSE-2.0\n"
"#\n"
"# Unless required by applicable law or agreed to in writing, software\n"
"# distributed under the License is distributed on an \"AS IS\" BASIS,\n"
"# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n"
"# See the License for the specific language governing permissions and\n"
"# limitations under the License.\n"
"\n"
"# This message can represent objects detected in a frame\n"
"std_msgs/Header header    # timestamp in header is the time the sensor captured the raw data\n"
"Object[] objects_vector   # Object array\n"
"float32 inference_time_ms # inference time of this frame. the unit is millisecond.\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: object_msgs/Object\n"
"# Copyright (c) 2017 Intel Corporation\n"
"#\n"
"# Licensed under the Apache License, Version 2.0 (the \"License\");\n"
"# you may not use this file except in compliance with the License.\n"
"# You may obtain a copy of the License at\n"
"#\n"
"#      http://www.apache.org/licenses/LICENSE-2.0\n"
"#\n"
"# Unless required by applicable law or agreed to in writing, software\n"
"# distributed under the License is distributed on an \"AS IS\" BASIS,\n"
"# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n"
"# See the License for the specific language governing permissions and\n"
"# limitations under the License.\n"
"\n"
"# This message define the property of detected object\n"
"string object_name  # object name\n"
"float32 probability # probability of detected object\n"
;
  }

  static const char* value(const ::object_msgs::ClassifyObjectResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::object_msgs::ClassifyObjectResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.objects);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ClassifyObjectResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::object_msgs::ClassifyObjectResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::object_msgs::ClassifyObjectResponse_<ContainerAllocator>& v)
  {
    s << indent << "objects[]" << std::endl;
    for (size_t i = 0; i < v.objects.size(); ++i)
    {
      s << indent << "  objects[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::object_msgs::Objects_<ContainerAllocator> >::stream(s, indent + "    ", v.objects[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // OBJECT_MSGS_MESSAGE_CLASSIFYOBJECTRESPONSE_H
