// Generated by gencpp from file object_msgs/ClassifyObjectRequest.msg
// DO NOT EDIT!


#ifndef OBJECT_MSGS_MESSAGE_CLASSIFYOBJECTREQUEST_H
#define OBJECT_MSGS_MESSAGE_CLASSIFYOBJECTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace object_msgs
{
template <class ContainerAllocator>
struct ClassifyObjectRequest_
{
  typedef ClassifyObjectRequest_<ContainerAllocator> Type;

  ClassifyObjectRequest_()
    : image_paths()  {
    }
  ClassifyObjectRequest_(const ContainerAllocator& _alloc)
    : image_paths(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _image_paths_type;
  _image_paths_type image_paths;





  typedef boost::shared_ptr< ::object_msgs::ClassifyObjectRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::object_msgs::ClassifyObjectRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ClassifyObjectRequest_

typedef ::object_msgs::ClassifyObjectRequest_<std::allocator<void> > ClassifyObjectRequest;

typedef boost::shared_ptr< ::object_msgs::ClassifyObjectRequest > ClassifyObjectRequestPtr;
typedef boost::shared_ptr< ::object_msgs::ClassifyObjectRequest const> ClassifyObjectRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::object_msgs::ClassifyObjectRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::object_msgs::ClassifyObjectRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::object_msgs::ClassifyObjectRequest_<ContainerAllocator1> & lhs, const ::object_msgs::ClassifyObjectRequest_<ContainerAllocator2> & rhs)
{
  return lhs.image_paths == rhs.image_paths;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::object_msgs::ClassifyObjectRequest_<ContainerAllocator1> & lhs, const ::object_msgs::ClassifyObjectRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace object_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::object_msgs::ClassifyObjectRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::object_msgs::ClassifyObjectRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::object_msgs::ClassifyObjectRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::object_msgs::ClassifyObjectRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::object_msgs::ClassifyObjectRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::object_msgs::ClassifyObjectRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::object_msgs::ClassifyObjectRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "072900a9ae5534db8c876cf096c6bdb1";
  }

  static const char* value(const ::object_msgs::ClassifyObjectRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x072900a9ae5534dbULL;
  static const uint64_t static_value2 = 0x8c876cf096c6bdb1ULL;
};

template<class ContainerAllocator>
struct DataType< ::object_msgs::ClassifyObjectRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "object_msgs/ClassifyObjectRequest";
  }

  static const char* value(const ::object_msgs::ClassifyObjectRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::object_msgs::ClassifyObjectRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Copyright (c) 2017 Intel Corporation\n"
"#\n"
"# Licensed under the Apache License, Version 2.0 (the \"License\");\n"
"# you may not use this file except in compliance with the License.\n"
"# You may obtain a copy of the License at\n"
"#\n"
"#      http://www.apache.org/licenses/LICENSE-2.0\n"
"#\n"
"# Unless required by applicable law or agreed to in writing, software\n"
"# distributed under the License is distributed on an \"AS IS\" BASIS,\n"
"# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n"
"# See the License for the specific language governing permissions and\n"
"# limitations under the License.\n"
"\n"
"string[] image_paths  # image path list for inference\n"
;
  }

  static const char* value(const ::object_msgs::ClassifyObjectRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::object_msgs::ClassifyObjectRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.image_paths);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ClassifyObjectRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::object_msgs::ClassifyObjectRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::object_msgs::ClassifyObjectRequest_<ContainerAllocator>& v)
  {
    s << indent << "image_paths[]" << std::endl;
    for (size_t i = 0; i < v.image_paths.size(); ++i)
    {
      s << indent << "  image_paths[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.image_paths[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // OBJECT_MSGS_MESSAGE_CLASSIFYOBJECTREQUEST_H
