// Generated by gencpp from file object_msgs/ClassifyObject.msg
// DO NOT EDIT!


#ifndef OBJECT_MSGS_MESSAGE_CLASSIFYOBJECT_H
#define OBJECT_MSGS_MESSAGE_CLASSIFYOBJECT_H

#include <ros/service_traits.h>


#include <object_msgs/ClassifyObjectRequest.h>
#include <object_msgs/ClassifyObjectResponse.h>


namespace object_msgs
{

struct ClassifyObject
{

typedef ClassifyObjectRequest Request;
typedef ClassifyObjectResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ClassifyObject
} // namespace object_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::object_msgs::ClassifyObject > {
  static const char* value()
  {
    return "530ab171b0ce2b4875431fb220cd7b7f";
  }

  static const char* value(const ::object_msgs::ClassifyObject&) { return value(); }
};

template<>
struct DataType< ::object_msgs::ClassifyObject > {
  static const char* value()
  {
    return "object_msgs/ClassifyObject";
  }

  static const char* value(const ::object_msgs::ClassifyObject&) { return value(); }
};


// service_traits::MD5Sum< ::object_msgs::ClassifyObjectRequest> should match
// service_traits::MD5Sum< ::object_msgs::ClassifyObject >
template<>
struct MD5Sum< ::object_msgs::ClassifyObjectRequest>
{
  static const char* value()
  {
    return MD5Sum< ::object_msgs::ClassifyObject >::value();
  }
  static const char* value(const ::object_msgs::ClassifyObjectRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::object_msgs::ClassifyObjectRequest> should match
// service_traits::DataType< ::object_msgs::ClassifyObject >
template<>
struct DataType< ::object_msgs::ClassifyObjectRequest>
{
  static const char* value()
  {
    return DataType< ::object_msgs::ClassifyObject >::value();
  }
  static const char* value(const ::object_msgs::ClassifyObjectRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::object_msgs::ClassifyObjectResponse> should match
// service_traits::MD5Sum< ::object_msgs::ClassifyObject >
template<>
struct MD5Sum< ::object_msgs::ClassifyObjectResponse>
{
  static const char* value()
  {
    return MD5Sum< ::object_msgs::ClassifyObject >::value();
  }
  static const char* value(const ::object_msgs::ClassifyObjectResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::object_msgs::ClassifyObjectResponse> should match
// service_traits::DataType< ::object_msgs::ClassifyObject >
template<>
struct DataType< ::object_msgs::ClassifyObjectResponse>
{
  static const char* value()
  {
    return DataType< ::object_msgs::ClassifyObject >::value();
  }
  static const char* value(const ::object_msgs::ClassifyObjectResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OBJECT_MSGS_MESSAGE_CLASSIFYOBJECT_H
