// Generated by gencpp from file object_msgs/DetectObject.msg
// DO NOT EDIT!


#ifndef OBJECT_MSGS_MESSAGE_DETECTOBJECT_H
#define OBJECT_MSGS_MESSAGE_DETECTOBJECT_H

#include <ros/service_traits.h>


#include <object_msgs/DetectObjectRequest.h>
#include <object_msgs/DetectObjectResponse.h>


namespace object_msgs
{

struct DetectObject
{

typedef DetectObjectRequest Request;
typedef DetectObjectResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DetectObject
} // namespace object_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::object_msgs::DetectObject > {
  static const char* value()
  {
    return "11b2ac83822624e9953f8718798e5220";
  }

  static const char* value(const ::object_msgs::DetectObject&) { return value(); }
};

template<>
struct DataType< ::object_msgs::DetectObject > {
  static const char* value()
  {
    return "object_msgs/DetectObject";
  }

  static const char* value(const ::object_msgs::DetectObject&) { return value(); }
};


// service_traits::MD5Sum< ::object_msgs::DetectObjectRequest> should match
// service_traits::MD5Sum< ::object_msgs::DetectObject >
template<>
struct MD5Sum< ::object_msgs::DetectObjectRequest>
{
  static const char* value()
  {
    return MD5Sum< ::object_msgs::DetectObject >::value();
  }
  static const char* value(const ::object_msgs::DetectObjectRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::object_msgs::DetectObjectRequest> should match
// service_traits::DataType< ::object_msgs::DetectObject >
template<>
struct DataType< ::object_msgs::DetectObjectRequest>
{
  static const char* value()
  {
    return DataType< ::object_msgs::DetectObject >::value();
  }
  static const char* value(const ::object_msgs::DetectObjectRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::object_msgs::DetectObjectResponse> should match
// service_traits::MD5Sum< ::object_msgs::DetectObject >
template<>
struct MD5Sum< ::object_msgs::DetectObjectResponse>
{
  static const char* value()
  {
    return MD5Sum< ::object_msgs::DetectObject >::value();
  }
  static const char* value(const ::object_msgs::DetectObjectResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::object_msgs::DetectObjectResponse> should match
// service_traits::DataType< ::object_msgs::DetectObject >
template<>
struct DataType< ::object_msgs::DetectObjectResponse>
{
  static const char* value()
  {
    return DataType< ::object_msgs::DetectObject >::value();
  }
  static const char* value(const ::object_msgs::DetectObjectResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OBJECT_MSGS_MESSAGE_DETECTOBJECT_H
