// Generated by gencpp from file object_msgs/ObjectsInBoxes.msg
// DO NOT EDIT!


#ifndef OBJECT_MSGS_MESSAGE_OBJECTSINBOXES_H
#define OBJECT_MSGS_MESSAGE_OBJECTSINBOXES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <object_msgs/ObjectInBox.h>

namespace object_msgs
{
template <class ContainerAllocator>
struct ObjectsInBoxes_
{
  typedef ObjectsInBoxes_<ContainerAllocator> Type;

  ObjectsInBoxes_()
    : header()
    , objects_vector()
    , inference_time_ms(0.0)  {
    }
  ObjectsInBoxes_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , objects_vector(_alloc)
    , inference_time_ms(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::object_msgs::ObjectInBox_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::object_msgs::ObjectInBox_<ContainerAllocator> >::other >  _objects_vector_type;
  _objects_vector_type objects_vector;

   typedef float _inference_time_ms_type;
  _inference_time_ms_type inference_time_ms;





  typedef boost::shared_ptr< ::object_msgs::ObjectsInBoxes_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::object_msgs::ObjectsInBoxes_<ContainerAllocator> const> ConstPtr;

}; // struct ObjectsInBoxes_

typedef ::object_msgs::ObjectsInBoxes_<std::allocator<void> > ObjectsInBoxes;

typedef boost::shared_ptr< ::object_msgs::ObjectsInBoxes > ObjectsInBoxesPtr;
typedef boost::shared_ptr< ::object_msgs::ObjectsInBoxes const> ObjectsInBoxesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::object_msgs::ObjectsInBoxes_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::object_msgs::ObjectsInBoxes_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::object_msgs::ObjectsInBoxes_<ContainerAllocator1> & lhs, const ::object_msgs::ObjectsInBoxes_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.objects_vector == rhs.objects_vector &&
    lhs.inference_time_ms == rhs.inference_time_ms;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::object_msgs::ObjectsInBoxes_<ContainerAllocator1> & lhs, const ::object_msgs::ObjectsInBoxes_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace object_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::object_msgs::ObjectsInBoxes_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::object_msgs::ObjectsInBoxes_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::object_msgs::ObjectsInBoxes_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::object_msgs::ObjectsInBoxes_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::object_msgs::ObjectsInBoxes_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::object_msgs::ObjectsInBoxes_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::object_msgs::ObjectsInBoxes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2c070e019267e39d554a36de7d183780";
  }

  static const char* value(const ::object_msgs::ObjectsInBoxes_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2c070e019267e39dULL;
  static const uint64_t static_value2 = 0x554a36de7d183780ULL;
};

template<class ContainerAllocator>
struct DataType< ::object_msgs::ObjectsInBoxes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "object_msgs/ObjectsInBoxes";
  }

  static const char* value(const ::object_msgs::ObjectsInBoxes_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::object_msgs::ObjectsInBoxes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Copyright (c) 2017 Intel Corporation\n"
"#\n"
"# Licensed under the Apache License, Version 2.0 (the \"License\");\n"
"# you may not use this file except in compliance with the License.\n"
"# You may obtain a copy of the License at\n"
"#\n"
"#      http://www.apache.org/licenses/LICENSE-2.0\n"
"#\n"
"# Unless required by applicable law or agreed to in writing, software\n"
"# distributed under the License is distributed on an \"AS IS\" BASIS,\n"
"# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n"
"# See the License for the specific language governing permissions and\n"
"# limitations under the License.\n"
"\n"
"# This message can represent objects detected and their bounding-boxes in a frame\n"
"std_msgs/Header header        # timestamp in header is the time the sensor captured the raw data\n"
"ObjectInBox[] objects_vector  # ObjectInBox array\n"
"float32 inference_time_ms     # inference time of this frame. the unit is millisecond.\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: object_msgs/ObjectInBox\n"
"# Copyright (c) 2017 Intel Corporation\n"
"#\n"
"# Licensed under the Apache License, Version 2.0 (the \"License\");\n"
"# you may not use this file except in compliance with the License.\n"
"# You may obtain a copy of the License at\n"
"#\n"
"#      http://www.apache.org/licenses/LICENSE-2.0\n"
"#\n"
"# Unless required by applicable law or agreed to in writing, software\n"
"# distributed under the License is distributed on an \"AS IS\" BASIS,\n"
"# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n"
"# See the License for the specific language governing permissions and\n"
"# limitations under the License.\n"
"\n"
"# This message can represent a detected object and its region of interest\n"
"Object object                     # detected object\n"
"sensor_msgs/RegionOfInterest roi  # region of interest\n"
"\n"
"================================================================================\n"
"MSG: object_msgs/Object\n"
"# Copyright (c) 2017 Intel Corporation\n"
"#\n"
"# Licensed under the Apache License, Version 2.0 (the \"License\");\n"
"# you may not use this file except in compliance with the License.\n"
"# You may obtain a copy of the License at\n"
"#\n"
"#      http://www.apache.org/licenses/LICENSE-2.0\n"
"#\n"
"# Unless required by applicable law or agreed to in writing, software\n"
"# distributed under the License is distributed on an \"AS IS\" BASIS,\n"
"# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n"
"# See the License for the specific language governing permissions and\n"
"# limitations under the License.\n"
"\n"
"# This message define the property of detected object\n"
"string object_name  # object name\n"
"float32 probability # probability of detected object\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/RegionOfInterest\n"
"# This message is used to specify a region of interest within an image.\n"
"#\n"
"# When used to specify the ROI setting of the camera when the image was\n"
"# taken, the height and width fields should either match the height and\n"
"# width fields for the associated image; or height = width = 0\n"
"# indicates that the full resolution image was captured.\n"
"\n"
"uint32 x_offset  # Leftmost pixel of the ROI\n"
"                 # (0 if the ROI includes the left edge of the image)\n"
"uint32 y_offset  # Topmost pixel of the ROI\n"
"                 # (0 if the ROI includes the top edge of the image)\n"
"uint32 height    # Height of ROI\n"
"uint32 width     # Width of ROI\n"
"\n"
"# True if a distinct rectified ROI should be calculated from the \"raw\"\n"
"# ROI in this message. Typically this should be False if the full image\n"
"# is captured (ROI not used), and True if a subwindow is captured (ROI\n"
"# used).\n"
"bool do_rectify\n"
;
  }

  static const char* value(const ::object_msgs::ObjectsInBoxes_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::object_msgs::ObjectsInBoxes_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.objects_vector);
      stream.next(m.inference_time_ms);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObjectsInBoxes_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::object_msgs::ObjectsInBoxes_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::object_msgs::ObjectsInBoxes_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "objects_vector[]" << std::endl;
    for (size_t i = 0; i < v.objects_vector.size(); ++i)
    {
      s << indent << "  objects_vector[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::object_msgs::ObjectInBox_<ContainerAllocator> >::stream(s, indent + "    ", v.objects_vector[i]);
    }
    s << indent << "inference_time_ms: ";
    Printer<float>::stream(s, indent + "  ", v.inference_time_ms);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OBJECT_MSGS_MESSAGE_OBJECTSINBOXES_H
