// Generated by gencpp from file object_msgs/ObjectInBox.msg
// DO NOT EDIT!


#ifndef OBJECT_MSGS_MESSAGE_OBJECTINBOX_H
#define OBJECT_MSGS_MESSAGE_OBJECTINBOX_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <object_msgs/Object.h>
#include <sensor_msgs/RegionOfInterest.h>

namespace object_msgs
{
template <class ContainerAllocator>
struct ObjectInBox_
{
  typedef ObjectInBox_<ContainerAllocator> Type;

  ObjectInBox_()
    : object()
    , roi()  {
    }
  ObjectInBox_(const ContainerAllocator& _alloc)
    : object(_alloc)
    , roi(_alloc)  {
  (void)_alloc;
    }



   typedef  ::object_msgs::Object_<ContainerAllocator>  _object_type;
  _object_type object;

   typedef  ::sensor_msgs::RegionOfInterest_<ContainerAllocator>  _roi_type;
  _roi_type roi;





  typedef boost::shared_ptr< ::object_msgs::ObjectInBox_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::object_msgs::ObjectInBox_<ContainerAllocator> const> ConstPtr;

}; // struct ObjectInBox_

typedef ::object_msgs::ObjectInBox_<std::allocator<void> > ObjectInBox;

typedef boost::shared_ptr< ::object_msgs::ObjectInBox > ObjectInBoxPtr;
typedef boost::shared_ptr< ::object_msgs::ObjectInBox const> ObjectInBoxConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::object_msgs::ObjectInBox_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::object_msgs::ObjectInBox_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::object_msgs::ObjectInBox_<ContainerAllocator1> & lhs, const ::object_msgs::ObjectInBox_<ContainerAllocator2> & rhs)
{
  return lhs.object == rhs.object &&
    lhs.roi == rhs.roi;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::object_msgs::ObjectInBox_<ContainerAllocator1> & lhs, const ::object_msgs::ObjectInBox_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace object_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::object_msgs::ObjectInBox_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::object_msgs::ObjectInBox_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::object_msgs::ObjectInBox_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::object_msgs::ObjectInBox_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::object_msgs::ObjectInBox_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::object_msgs::ObjectInBox_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::object_msgs::ObjectInBox_<ContainerAllocator> >
{
  static const char* value()
  {
    return "658b4f57dcac376ed1902dc618650a32";
  }

  static const char* value(const ::object_msgs::ObjectInBox_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x658b4f57dcac376eULL;
  static const uint64_t static_value2 = 0xd1902dc618650a32ULL;
};

template<class ContainerAllocator>
struct DataType< ::object_msgs::ObjectInBox_<ContainerAllocator> >
{
  static const char* value()
  {
    return "object_msgs/ObjectInBox";
  }

  static const char* value(const ::object_msgs::ObjectInBox_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::object_msgs::ObjectInBox_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Copyright (c) 2017 Intel Corporation\n"
"#\n"
"# Licensed under the Apache License, Version 2.0 (the \"License\");\n"
"# you may not use this file except in compliance with the License.\n"
"# You may obtain a copy of the License at\n"
"#\n"
"#      http://www.apache.org/licenses/LICENSE-2.0\n"
"#\n"
"# Unless required by applicable law or agreed to in writing, software\n"
"# distributed under the License is distributed on an \"AS IS\" BASIS,\n"
"# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n"
"# See the License for the specific language governing permissions and\n"
"# limitations under the License.\n"
"\n"
"# This message can represent a detected object and its region of interest\n"
"Object object                     # detected object\n"
"sensor_msgs/RegionOfInterest roi  # region of interest\n"
"\n"
"================================================================================\n"
"MSG: object_msgs/Object\n"
"# Copyright (c) 2017 Intel Corporation\n"
"#\n"
"# Licensed under the Apache License, Version 2.0 (the \"License\");\n"
"# you may not use this file except in compliance with the License.\n"
"# You may obtain a copy of the License at\n"
"#\n"
"#      http://www.apache.org/licenses/LICENSE-2.0\n"
"#\n"
"# Unless required by applicable law or agreed to in writing, software\n"
"# distributed under the License is distributed on an \"AS IS\" BASIS,\n"
"# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n"
"# See the License for the specific language governing permissions and\n"
"# limitations under the License.\n"
"\n"
"# This message define the property of detected object\n"
"string object_name  # object name\n"
"float32 probability # probability of detected object\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/RegionOfInterest\n"
"# This message is used to specify a region of interest within an image.\n"
"#\n"
"# When used to specify the ROI setting of the camera when the image was\n"
"# taken, the height and width fields should either match the height and\n"
"# width fields for the associated image; or height = width = 0\n"
"# indicates that the full resolution image was captured.\n"
"\n"
"uint32 x_offset  # Leftmost pixel of the ROI\n"
"                 # (0 if the ROI includes the left edge of the image)\n"
"uint32 y_offset  # Topmost pixel of the ROI\n"
"                 # (0 if the ROI includes the top edge of the image)\n"
"uint32 height    # Height of ROI\n"
"uint32 width     # Width of ROI\n"
"\n"
"# True if a distinct rectified ROI should be calculated from the \"raw\"\n"
"# ROI in this message. Typically this should be False if the full image\n"
"# is captured (ROI not used), and True if a subwindow is captured (ROI\n"
"# used).\n"
"bool do_rectify\n"
;
  }

  static const char* value(const ::object_msgs::ObjectInBox_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::object_msgs::ObjectInBox_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.object);
      stream.next(m.roi);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObjectInBox_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::object_msgs::ObjectInBox_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::object_msgs::ObjectInBox_<ContainerAllocator>& v)
  {
    s << indent << "object: ";
    s << std::endl;
    Printer< ::object_msgs::Object_<ContainerAllocator> >::stream(s, indent + "  ", v.object);
    s << indent << "roi: ";
    s << std::endl;
    Printer< ::sensor_msgs::RegionOfInterest_<ContainerAllocator> >::stream(s, indent + "  ", v.roi);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OBJECT_MSGS_MESSAGE_OBJECTINBOX_H
